const reference = [
  {
    author: "23Audiovisual",
    title: "",
    year: "2023",
    sourceTitle: "",
    link: "https://www.pexels.com/ko-kr/video/17246777/",
  },
  {
    author: "Brian Yurasits",
    title: "해변에 물 플라스틱 병",
    year: "2019",
    sourceTitle: "",
    link: "https://unsplash.com/ko/%EC%82%AC%EC%A7%84/5fbJMCzqNDs",
  },
  {
    author: "Naja Bertolt Jensen",
    title: "",
    year: "2022",
    sourceTitle: "",
    link: "https://unsplash.com/ko/%EC%82%AC%EC%A7%84/V8EdKmpj974",
  },
  {
    author: "giogio55",
    title: "",
    year: "2015",
    sourceTitle: "",
    link: "https://pixabay.com/ko/photos/%EB%B0%94%EB%8B%A4-%ED%9D%99-%EC%93%B0%EB%A0%88%EA%B8%B0-%EC%98%A4%EC%97%BC-1017596/",
  },
  {
    author: "Reinis Birznieks",
    title: "",
    year: "2018",
    sourceTitle: "",
    link: "https://unsplash.com/ko/%EC%82%AC%EC%A7%84/lu5uhEAy2lI",
  },
  {
    author: "jaemin don",
    title: "",
    year: "2020",
    sourceTitle: "",
    link: "https://unsplash.com/ko/%EC%82%AC%EC%A7%84/k4DK_xyr5Yc",
  },
  {
    author: "Aaron Burden",
    title: "",
    year: "2016",
    sourceTitle: "",
    link: "https://unsplash.com/ko/%EC%82%AC%EC%A7%84/cEukkv42O40",
  },
  {
    author: "세계유산한라산연구부",
    title: "",
    year: "",
    sourceTitle: "제주도 지질공원",
    link: "http://www.jeju.go.kr/geopark/intro/udo/images.htm",
  },
  {
    author: "윤영혜",
    title: "전세계 바다에 떠다니는 미세플라스틱 무려 230만톤",
    year: "2023",
    sourceTitle: "동아사이언스",
    link: "http://m.dongascience.com/news.php?idx=58895",
  },
  {
    author: "김민정",
    title: "해양 플라스틱, 새로운 미생물 생태계...인간 병원체 증식 빨라",
    year: "2022",
    sourceTitle: "ESG경제",
    link: "http://www.esgeconomy.com/news/articleView.html?idxno=2395",
  },
  {
    author: "한국환경보건학회",
    title:
      "2016년도 국내 해양환경내 병원성 비브리오균의 분포 및 해양환경인자간의 상관성 분석",
    year: "2018",
    sourceTitle: "한국환경보건학회지",
    link: "https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002342259",
  },
];
